language: go
sudo: false
matrix:
  include:
  - go: 1.x
    env: GOOS=linux GOARCH=amd64


install:
- true # skip

script:
- go get -u github.com/golang/dep/cmd/dep
- dep ensure
- go build .

deploy:
  provider: releases
  api_key:
    secure: Gokt5QRGOtEt0ckJfGSx4xSlbyX4jOVCTu3d+CiH77nN5MacxGvKQZNEbcQ9pmAu4LmvZ4tv8wDBv/RWhH5MsEr0bmt5TVK5z45PFwtP731dGMiaZlCz5tg3m9gaJDiEVeacjAWqzRBedSZsJAOA6jpZAhDkjkKqiy6DnDnTa+EHj33IEZJRNtKhWgzGXgzHauAyPeNAHG80Lr12iQWcY7jvfPV1fyCnaiGpuuVTLyQRB4Yiskk9H6IMxblFQpGJvu4l23npecmZg8ss/0yQSWdGzQnCtUlbaOGQjrpmDn3rveUzm2Fzs2vh5C4CYzmpJFjXw2ZkxnKf+7YvWnlWsVriIgCPqWM/hPgobu5X2V6BzVRu+uLgqhWTN+1klWP9oS3oUggAx4KgTeNABW5RXU/r36yVCqh4s3GtK5gLwbL/Ufs0ZSBQoiDjyLaRF7VyPCqEHOQBowEECBRcVsuMpVpUBQyZX8HODJEM1vz9cfhjJdWm8Q+dAGHsemoeQ1T8nM9obgKw5pffr/6t/zvWt8xvCvsC720D9bLFoXgRhwrqyk8R058sBF832ohQnhbRnXfqrRBeZhoZ301Wv8HSYPpQnBf+ZwFqHMXDRgTLvIcVHq7niJj5EthXFIWS3m5D3eaB+N8k6cJrAC0iEH3vpQJobwImQA0vpnV2DqnIbbY=
  file: ec2router
  on:
    repo: radhus/ec2router
